services:
  server:
    build: ./Server-GRPC
    container_name: rpc-server
    ports:
      - "50051:50051"
    networks:
      - mynet
    volumes:
      - ./src:/data

  client:
    build: ./Client-GRPC
    container_name: rpc-client
    depends_on:
      - server
    networks:
      - mynet
    volumes:
      - ./src:/data
    stdin_open: true
    tty: true

networks:
  mynet:
    driver: bridge
