#version: "3.8"

services:
  server:
    build: ./Server-gRPC
    ports:
      - "50051:50051"
    volumes:
      - ./src:/data

  client:
    build: ./Client-gRPC
    depends_on:
      - server
    volumes:
      - ./src:/data
    stdin_open: true #teclado ligado ao container
    tty: true #cria um terminal fake
